**************************************2016/01/12_15:00:55******************************************
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/PS_KK
/home/mtx/github/Tide/src/TIDES.py:114: RuntimeWarning: invalid value encountered in sqrt
  return (fk(k)/Pk(k)/Q)**0.5/k
/home/zhm/haloes/halorhobin1024m2z0.000.dat
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/
Loading data.................
Save data....................
calculating deltaW...........
deltagx is ok
deltagy is ok
calculating gamma............
calculating kappa_3dx........
calculating kappa_3dx......OK
Save data....................
Loading data.................
Save data....................
Save data....................
Save data....................
step 1 ok
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/PS_KK
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/
Loading hdf5
Loading data.................
Save data....................
Save data....................
Save data....................
step 2 ok
********************************************************************************
**************************************2016/01/12_23:04:02******************************************
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/PS_KK
/home/mtx/github/Tide/src/TIDES.py:114: RuntimeWarning: invalid value encountered in sqrt
  return (fk(k)/Pk(k)/Q)**0.5/k
/home/zhm/haloes/halorhobin1024m2z0.000.dat
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/
Loading data.................
Save data....................
calculating deltaW...........
deltagx is ok
deltagy is ok
calculating gamma............
calculating kappa_3dx........
calculating kappa_3dx......OK
Save data....................
Loading data.................
Save data....................
Save data....................
Save data....................
step 1 ok
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/PS_KK
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth2.5_m2/
Loading hdf5
Loading data.................
Save data....................
Save data....................
Save data....................
step 2 ok
********************************************************************************
**************************************2016/01/13_12:09:17******************************************
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/PS_KK
/home/mtx/github/Tide/src/TIDES.py:115: RuntimeWarning: invalid value encountered in sqrt
  return (fk(k)/Pk(k)/Q)**0.5/k
/home/zhm/haloes/halorhobin1024m3z0.000.dat
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/
Loading data.................
Save data....................
calculating deltaW...........
deltagx is ok
deltagy is ok
calculating gamma............
calculating kappa_3dx........
calculating kappa_3dx......OK
Save data....................
Loading data.................
Save data....................
Save data....................
Save data....................
step 1 ok
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/PS_KK
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/
Loading hdf5
Loading data.................
Save data....................
Save data....................
Save data....................
step 2 ok
********************************************************************************
**************************************2016/01/13_16:07:18******************************************
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/PS_KK
/home/mtx/github/Tide/src/TIDES.py:115: RuntimeWarning: invalid value encountered in sqrt
  return (fk(k)/Pk(k)/Q)**0.5/k
/home/zhm/haloes/halorhobin1024m3z0.000.dat
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/
Loading data.................
Save data....................
calculating deltaW...........
deltagx is ok
deltagy is ok
calculating gamma............
calculating kappa_3dx........
calculating kappa_3dx......OK
Save data....................
Loading data.................
Save data....................
Save data....................
Save data....................
step 1 ok
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/PS_KK
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth3.5_m3/
Loading hdf5
Loading data.................
Save data....................
Save data....................
Save data....................
step 2 ok
********************************************************************************
**************************************2016/01/13_21:14:07******************************************
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/PS_KK
/home/zhm/haloes/halorhobin1024m3z0.000.dat
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/
Loading data.................
Traceback (most recent call last):
  File "result.py", line 14, in <module>
    halo_x=Tide.LoadData(filename=Inputfilename)
  File "/home/mtx/github/Tide/src/TIDES.py", line 25, in LoadData
    data = np.array(data, dtype=np.float)
KeyboardInterrupt
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
: unable to open file (File accessibilty: Unable to open file)
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
Traceback (most recent call last):
  File "get_bin2d1.py", line 20, in <module>
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
    f=h5py.File('/home/mtx/data/tide/outdata/'+name+'/halo/'+name2+'/0.000halo00_Pk_delta.hdf5','r')
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:2041)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
IOError: unable to open file (File accessibilty: Unable to open file)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[44147,1],31]
  Exit code:    1
--------------------------------------------------------------------------
step 1 ok
cp: 无法获取"/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/result_b" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/result_W" 的文件状态(stat): 没有那个文件或目录
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/PS_KK
Killed by signal 2.
Killed by signal 2.
Traceback (most recent call last):
  File "get_wfPk.py", line 4, in <module>
    from TIDES import *
  File "/home/mtx/github/Tide/src/TIDES.py", line 6, in <module>
    import scipy.interpolate as interpolate
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/scipy/interpolate/__init__.py", line 160, in <module>
    from .ndgriddata import *
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/scipy/interpolate/ndgriddata.py", line 10, in <module>
    from .interpnd import LinearNDInterpolator, NDInterpolatorBase, \
  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd (scipy/interpolate/interpnd.c:22803)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/scipy/spatial/__init__.py", line 90, in <module>
    from ._plotutils import *
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/scipy/spatial/_plotutils.py", line 4, in <module>
    from scipy.lib.decorator import decorator as _decorator
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/scipy/lib/decorator.py", line 37, in <module>
    import sys, re, inspect
  File "/opt/python-2.7.5-mkl/lib/python2.7/inspect.py", line 39, in <module>
    import tokenize
  File "/opt/python-2.7.5-mkl/lib/python2.7/tokenize.py", line 102, in <module>
    re.compile, (Token, PseudoToken, Single3, Double3))
  File "/opt/python-2.7.5-mkl/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/opt/python-2.7.5-mkl/lib/python2.7/re.py", line 240, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_compile.py", line 501, in compile
    p = sre_parse.parse(p, flags)
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_parse.py", line 686, in parse
    p = _parse_sub(source, pattern, 0)
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_parse.py", line 309, in _parse_sub
    itemsappend(_parse(source, state))
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_parse.py", line 646, in _parse
    p = _parse_sub(source, state)
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_parse.py", line 309, in _parse_sub
    itemsappend(_parse(source, state))
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_parse.py", line 646, in _parse
    p = _parse_sub(source, state)
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_parse.py", line 309, in _parse_sub
    itemsappend(_parse(source, state))
  File "/opt/python-2.7.5-mkl/lib/python2.7/sre_parse.py", line 517, in _parse
    if not item or (_len(item) == 1 and item[0][0] == AT):
KeyboardInterrupt
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
step 2 ok
********************************************************************************
**************************************2016/01/13_21:20:01******************************************
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/PS_KK
/home/mtx/github/Tide/src/TIDES.py:115: RuntimeWarning: invalid value encountered in sqrt
  return (fk(k)/Pk(k)/Q)**0.5/k
/home/zhm/haloes/halorhobin1024m3z0.000.dat
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/
Loading data.................
Save data....................
calculating deltaW...........
deltagx is ok
deltagy is ok
calculating gamma............
calculating kappa_3dx........
calculating kappa_3dx......OK
Save data....................
Loading data.................
Save data....................
Save data....................
Save data....................
step 1 ok
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/0.000halo00_wfPk_kappa.hdf5 /home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/PS_KK
/home/mtx/data/tide/outdata/haloes/halo/bias_smooth5.0_m3/
Loading hdf5
Loading data.................
Save data....................
Save data....................
Save data....................
step 2 ok
********************************************************************************
